import type { ListState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: ListState, fileName = "list") : ExportPayload {
  return { fileName: `${fileName || "list"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: ListState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
    "",
    "function resolveFont(s) { return s.fontBucket === \"google\" ? '\"' + s.googleFontFamily + '\", sans-serif' : \"inherit\"; }",
    "function buildShadow(s) { if (!s.shadowEnabled) return \"none\"; var hex = Math.round(s.shadowOpacity * 255).toString(16).padStart(2, \"0\"); return s.shadowX + \"px \" + s.shadowY + \"px \" + s.shadowBlur + \"px \" + s.shadowSpread + \"px \" + s.shadowColor + hex; }",
    "",
    "function itemStatus(selected) {",
    "  if (selected) return \"Selected\";",
    "  if (state.previewState === \"error\") return \"Needs review\";",
    "  if (state.previewState === \"success\") return \"Complete\";",
    "  if (state.previewState === \"loading\") return \"Syncing\";",
    "  return \"Ready\";",
    "}",
    "",
    "export default function ListComponent() {",
    "  const itemTotal = state.emptyState ? 0 : Math.max(state.itemCount, 1);",
    "  const items = Array.from({ length: itemTotal }, (_, index) => index);",
    "  const selectedIndex = Math.min(Math.max(state.selectedIndex, 0), Math.max(itemTotal - 1, 0));",
    "  const ListTag = state.listMode === \"ordered\" ? \"ol\" : \"ul\";",
    "  const listRole = state.listMode === \"menu\" || state.listMode === \"listbox\" ? state.listMode : undefined;",
    "  const itemRole = state.listMode === \"menu\" ? \"menuitem\" : state.listMode === \"listbox\" ? \"option\" : undefined;",
    "  const [hoverIndex, setHoverIndex] = React.useState(-1);",
    "  const panel = { width: state.width, minHeight: state.height, padding: state.padding, borderRadius: state.radius + \"px\", border: state.borderWidth + \"px \" + (state.borderStyle ?? \"solid\") + \" \" + (state.disabled && state.disabledUseCustomColors ? state.disabledBorder : state.border), boxShadow: buildShadow(state), background: state.disabled && state.disabledUseCustomColors ? state.disabledBg : state.background, color: state.foreground, fontFamily: resolveFont(state), opacity: state.disabled ? (state.disabledOpacity ?? 0.5) : 1, cursor: state.disabled ? state.disabledCursor : undefined, transition: (state.transitionDuration > 0) ? \"opacity \" + state.transitionDuration + \"ms \" + (state.transitionEasing ?? \"ease\") : \"none\" };",
    "  return (",
    "    <section id={state.id} aria-labelledby={`${state.id}-title`} aria-describedby={`${state.id}-description ${state.id}-count`} tabIndex={state.tabIndex} style={panel} data-component=\"list\" data-preview-state={state.previewState}>",
    "      <div style={{ marginBottom: 16 }}>",
    "        <h3 id={`${state.id}-title`} style={{ fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h3>",
    "        <p id={`${state.id}-description`} style={{ color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "        <p id={`${state.id}-count`} style={{ color: state.muted, fontSize: 12, marginTop: 8 }}>{itemTotal} {itemTotal === 1 ? \"item\" : \"items\"} in this {state.listMode} list.</p>",
    "      </div>",
    "      {state.emptyState ? (",
    "        <p role=\"status\" style={{ border: state.borderWidth + \"px \" + state.borderStyle + \" \" + state.border, borderRadius: Math.max(state.radius - 6, 10), padding: 16, color: state.muted }}>{state.helper}</p>",
    "      ) : (",
    "        <ListTag role={listRole} aria-label={`${state.ariaLabel}: ${itemTotal} items`} style={{ display: \"grid\", gap: state.gap, listStyle: \"none\", padding: 0, margin: 0 }}>",
    "          {items.map((index) => {",
    "            const selected = index === selectedIndex;",
    "            const hovered = hoverIndex === index && !selected && !state.disabled;",
    "            const status = itemStatus(selected);",
    "            const itemBackground = selected ? state.itemActiveBg : hovered ? state.itemHoverBg : state.itemBg;",
    "            const itemColor = state.disabled ? state.itemDisabledColor : selected ? state.itemSelectedText : hovered ? state.itemHoverText : state.itemText;",
    "            const itemBorderColor = selected ? state.itemSelectedBorder : state.showDividers ? state.dividerColor : \"transparent\";",
    "            return (",
    "              <li key={index} role={itemRole} aria-selected={state.listMode === \"listbox\" ? selected : undefined} aria-disabled={state.disabled || undefined} onMouseEnter={() => setHoverIndex(index)} onMouseLeave={() => setHoverIndex(-1)} style={{ display: \"flex\", alignItems: \"center\", gap: 12, minHeight: state.itemHeight, borderRadius: state.itemRadius, border: state.borderWidth + \"px \" + state.dividerStyle + \" \" + itemBorderColor, padding: state.itemPadding, background: itemBackground, color: itemColor, transition: state.transitionDuration > 0 ? \"background 200ms ease, border-color 200ms ease, color 200ms ease\" : \"none\" }}>",
    "                {state.showAvatars && <span aria-hidden=\"true\" style={{ display: \"grid\", placeItems: \"center\", width: state.avatarSize, height: state.avatarSize, borderRadius: 999, background: selected ? state.accent : state.border, color: state.leadingIconColor, fontWeight: 700 }}>{index + 1}</span>}",
    "                <span style={{ minWidth: 0, flex: 1 }}>",
    "                  <span style={{ display: \"block\", fontWeight: 700 }}>{state.label} {index + 1}</span>",
    "                  <span style={{ display: \"block\", color: state.secondaryTextColor, fontSize: state.secondaryTextSize }}>{state.helper}</span>",
    "                </span>",
    "                <span style={{ border: state.borderWidth + \"px \" + state.borderStyle + \" \" + state.badgeBorder, borderRadius: state.badgeRadius, padding: \"4px 8px\", background: state.badgeBg, color: state.badgeText, fontSize: 12 }}>{status}</span>",
    "              </li>",
    "            );",
    "          })}",
    "        </ListTag>",
    "      )}",
    "    </section>",
    "  );",
    "}",
    "",
  ].join("\n");
}
